name: ZAP Baseline Scan

on:
  push

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t cicd-demo:test .

      - name: Run application
        run: |
          docker run -d -p 3000:3000 --name app cicd-demo:test
          timeout 60 bash -c 'until curl -f http://localhost:3000/; do sleep 2; done'

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:3000"

      - name: Cleanup
        if: always()
        run: docker stop app && docker rm app
